<?php $_productCollection = $this->getBestsellerProducts(); ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php if($_productCollection->count()) : ?>
<div class="block best-selling">
    <div class="block-title">
        <strong><span><?php echo $this->__('Best Selling Products') ?></span></strong>
    </div>
    <div class="block-content">
    <ul>
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item">
            <p class="product-name">
                <a href="<?php echo $_product->getProductUrl() ?>"
                   title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                    <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                </a>
            </p>
            <img class="product-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>"  width="95" border="0" />
        </li>
    <?php endforeach; ?>
    </ul>
    </div>
</div>
<?php else: ?>
    <?php echo $this->__(Mage::getStoreConfig('sam_bestsellers/settings/message_text')); ?>
<?php endif; ?>